### ISSUE TITLE
All knectar blog post links in resume are now 404

### ISSUE THREAD

**Issue by rfay** [sanguis/cv#3]
These blog links are now 404, hopefully you have a copy of them that can be put elsewhere.

* https://www.knectar.com/labs/streamlining%20deployments%20beanstalk
* https://www.knectar.com/labs/%E2%80%9Clinkit%20target%E2%80%9D%20module%20released%20drupalorg
* https://www.knectar.com/labs/selecting%20default%20input%20format%20filtered%20text%20drupal%207%20better%20ux

Isn't it crazy how online stuff rots?

**Comment by sanguis** [comment]
Its true, I dont work for that company anymore and they updated thirs links. its on my todo list to get this sorted thanks
